### ISSUE TITLE
definir a forma de execução do programa de instalação (ref. lombok clicando 2 vezes é como se fosse um executavel).

### ISSUE THREAD

**Issue by flauberjp** [flauberjp/my-git-usage-evidences#10]
Uma fonte de inspiração pode ser o dbeaver, que é um programa Java e possui instalador, poderiamos verificar como isso funciona lá e adotar do nosso lado.
Link do repo do dbeaver: https://github.com/dbeaver/dbeaver

**Comment by flauberjp** [comment]
@rodrigobarbosa por acaso vi isso, parece ser um plugin do maven que empacota a solução em um .exe: 
https://github.com/violetumleditor/violetumleditor/blob/master/violetproduct-exe/pom.xml

**Comment by rodrigobarbosa** [comment]
@flauberjp boa sugestão. Como ainda não havia avançado com a tarefa, aparenta ser uma boa solução. Preciso testar ela pra ver se supre nossa necessidade.

**Comment by flauberjp** [comment]
Esse artigo fala sobre uma solução que poderiamos reusar: https://medium.com/@adam_carroll/java-packager-with-jdk11-31b3d620f4a8

**Comment by flauberjp** [comment]
É possível gerar um .exe com o Launch4j, ver em: https://medium.com/@sulabh4/how-to-make-a-executable-file-from-your-java-code-3f521938ae5c

**Comment by flauberjp** [comment]
É possível modificar o registry do windows configurando um .exe para ser executado pelo administrador, ver em: https://stackoverflow.com/questions/16978917/how-to-set-run-as-administrator-on-a-file-using-inno-setup?noredirect=1&lq=1

**Comment by flauberjp** [comment]
Ver como gerar o instalador em: [Como gerar o programa de instalação](https://github.com/flauberjp/my-git-usage-evidences/wiki/Como-gerar-o-programa-de-instala%C3%A7%C3%A3o)
