### ISSUE TITLE
VIABILIDADE DO GRAALVM

### ISSUE THREAD

**Issue by rodrigobarbosa** [flauberjp/my-git-usage-evidences#4]
pesquisar a viabilidade de gerar codigo nativo usando o graalvm

**Comment by flauberjp** [comment]
@rodrigobarbosa eu tinha começado essa pesquisa, o que achei segue abaixo, talvez ajude :

- Exemplo de geração de código nativa, mas de um web app usando o Tomcat: https://www.infoq.com/news/2020/03/graalvm-20-tomcat-native-windows/

- Pre requisitos do Graalvm, no windows tem uns programas a parte que o cara tem que instalar, acho que se instalar o Visual Studio 2019 Community é suficiente: https://www.graalvm.org/docs/reference-manual/native-image/#prerequisites

- Comando: para baixar o native-image no windows : _gu install native-image_ no bin do graalvm. Depois tem esse aqui: native-image -jar my-git-usage-evidences-1.0-SNAPSHOT-jar-with-dependencies.jar. Esse .jar é o que geramos usando o lifecycle do mavem package.

**Comment by flauberjp** [comment]
@rodrigobarbosa é punk fazer isso funcionar no windows eheh
eu tava vendo o quarkus, q tem um procedimento pra vc criar uma app nativa no windows usando ele, as instruções estão aqui: https://quarkus.io/guides/building-native-image
eu pensei no seguinte, se seguirmos esse tutorial ai e conseguirmos gerar uma imagem no windows... acho que a partir dai poderiamos modificar a solução pra nossa necessidade e depois regerar a imagem navita, so que agora usando o nosso codigo java.

**Comment by flauberjp** [comment]
@rodrigobarbosa nessa [issue ](https://github.com/oracle/graal/issues/1327)há uma indicação que não é possível no momento usar o native image e o swing juntos, daí acho melhor abandonarmos esse esforço por hora. 

Eu criei uma outra [task  ](https://github.com/flauberjp/my-git-usage-evidences/projects/1#card-38888949) que foca em fazer a instalação de forma mais tradicional, vc pode pega-la?
